# Generated by Django 5.0 on 2024-05-01 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 10, 16, 22, 4574)),
        ),
        migrations.AlterField(
            model_name='income',
            name='value',
            field=models.IntegerField(choices=[('choice1', 'choice2')], default='choice1'),
        ),
    ]
