# Generated by Django 5.0 on 2024-05-01 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0002_alter_income_date_alter_income_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 10, 51, 26, 879068)),
        ),
        migrations.AlterField(
            model_name='income',
            name='value',
            field=models.IntegerField(choices=[('income', 'expense'), ('expense', 'income')]),
        ),
    ]
