# Generated by Django 5.0 on 2024-05-02 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0003_alter_income_date_alter_income_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expense', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 5, 2, 9, 5, 37, 60906))),
            ],
        ),
        migrations.RemoveField(
            model_name='income',
            name='value',
        ),
        migrations.AddField(
            model_name='income',
            name='income',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 9, 5, 37, 60906)),
        ),
    ]
