# Generated by Django 5.0 on 2024-05-02 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0004_expense_remove_income_value_income_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense',
            new_name='ex_pense',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='income',
            new_name='in_come',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 9, 19, 55, 545615)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 9, 19, 55, 544617)),
        ),
    ]
