# Generated by Django 5.0 on 2024-05-02 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0005_rename_expense_expense_ex_pense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='in_come',
        ),
        migrations.AddField(
            model_name='income',
            name='type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 9, 21, 55, 238158)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 9, 21, 55, 237132)),
        ),
    ]
