# Generated by Django 5.0 on 2024-05-02 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0007_alter_expense_date_alter_income_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 9, 38, 48, 722480)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 9, 38, 48, 721482)),
        ),
    ]
