# Generated by Django 5.0 on 2024-05-02 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0008_income_amount_alter_expense_date_alter_income_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='expense',
        ),
        migrations.AddField(
            model_name='income',
            name='balance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 10, 30, 21, 815054)),
        ),
    ]
