# Generated by Django 5.0 on 2024-05-02 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0009_delete_expense_income_balance_alter_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 10, 32, 19, 339569)),
        ),
    ]
