# Generated by Django 5.0.4 on 2024-05-09 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0010_alter_income_balance_alter_income_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='balance',
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 17, 45, 35, 934014)),
        ),
    ]
